--- #Error handling example #2
- hosts: localhost
  become: yes
  vars:
    target_service: httpd
  tasks:
    - name: Install software
      block:  #using block groups for debugging 
        - service:
            name: "{{ target_service }}"
            state: started 
          register: service_status
      rescue: #using block groups for debugging | enters here only if block fails 
        - debug:
            var: service_status
        # another debug acan be added with another var if needed 
      always: #using block groups for debugging | always executed, not mandatory 
        - debug:
            msg: "Tried to ensure service is running"


