--- #Error handling example #1
- hosts: localhost
  become: yes
  tasks:
    - name: Install software
      yum:
        name: broke
        state: latest
      ignore_errors: yes
    - name: Run utility
      command: /home/ansible/github/la-ansible-projects/handling-errors/do-stuff.sh # we are passing value to a shell script 
      register: cmd_output
      changed_when: " 'CHANGED' in cmd_output.stdout "
      failed_when: " 'FAIL' in cmd_output.stdout "
