--- #Serial execution Example
- hosts: all 
  #max_fail_percentage: 10 #if 10% fails it will stop deployment 
  #serial: 1 #allows to batch hosts for particular tasks | execution will be done 1 by 1 on each host.
  serial:
  - 1 # "10%" we can mix it as well | 1
  - 3 # "30%" | 30%
  - 5 # "50%" #in case more then 5 fork needs to be edited either in ansible.cfg or by using -f flag
  become: yes
  tasks:
    - name: install elinks 
      package:
        name: elinks 
        state: latest
