--- #Vault Example
- hosts: localhost
  vars_files:
    /home/ansible/github/la-ansible-projects/ansible-vault/vault  #file that contains password
  tasks:
    - name: Add secret test to open.txt
      lineinfile:
        path: /home/ansible/github/la-ansible-projects/ansible-vault/open.txt
        create: yes
        line: "{{ password }}"
      no_log: true #password can be exposed using verbosity level or debug
